name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package

    - name: Deploy to repository
      if: github.ref == 'refs/heads/master'
      run: mvn -B deploy -Dregistry=https://maven.pkg.github.com/ctron -Dtoken=${{ secrets.GITHUB_TOKEN }}
